// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrtkcumoadcwairxnagq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpydGtjdW1vYWRjd2FpcnhuYWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjU5MjAsImV4cCI6MjA3MjMwMTkyMH0.kpgrnJ1hwhL6qghqEF0B9AEnNH-JBadA-wzjuOkAlbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});